name: Frontend CI/CD Workflow

on:
  push:
    branches:
      - main
      - 'structure/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test Frontend
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          npm install
          npm audit fix # Automatically fix vulnerabilities

      # Step 4: Run linting
      - name: Run Linter
        run: npm run lint

      # Step 5: Build the project
      - name: Build Project
        run: npm run build

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
